### ISSUE TITLE
File Encoding

### ISSUE THREAD

**Issue by KarlZeilhofer** [RevolutionPi/IODeviceExample#1]
Hi, 

thank you very much, that you have been able to publish this firmware. 

I just had a look into it, it compiled without any problems!

Is there any plan, that the file encoding is translated into the standard UTF-8 format?

Greets from Austria, 
Karl

**Comment by KarlZeilhofer** [comment]
PS: I could do the translation, if I know, the pull request gets merged.

**Comment by mduckeck** [comment]
Hi Karl,
please make the changes. I will accept your pull requests, of Course.
kind regards
Mathias
