### ISSUE TITLE
What are the Differences to a shipped DIO-Firmware?

### ISSUE THREAD

**Issue by KarlZeilhofer** [RevolutionPi/IODeviceExample#4]
Does my DIO module behave exactly the same with the custom compiled firmware as with the shipped firmware?

How about any bootloader? Are the modules shipped with a bootloader which can accept a new firmware directly from the Revpi Core via the RS485? If so, is this bootloader included in this repo?

**Comment by mduckeck** [comment]
Hi Karl,
source code is the same as the one we use in the shipped module. But your guess is correct. The code for the firmware update is missing.

**Comment by KarlZeilhofer** [comment]
@mduckeck So if I flash this slef compiled firmware into my DIO module, it will behave identical?
What about the serial number?

**Comment by mduckeck** [comment]
Yes, it should have the same behaviour.
There is a global variable ctKunbusFirmwareSecriptor_g in the File FW_Desc.c. The second value is the serial number (0xffffffff).
