### ISSUE TITLE
Error in Memory Map File?

### ISSUE THREAD

**Issue by KarlZeilhofer** [RevolutionPi/IODeviceExample#5]
Hi, 

I just tried to flash the compiled firmware onto our Makerboard, which is basically a DIO Hardware. 

I used the black magic probe and went along with the tutorial from the manufacturer of that black magic probe: https://www.youtube.com/watch?v=ANM0fdAqDow

At the GDB command `load` I got the message: 
```
(gdb) load
Loading section .isrVec, size 0x184 lma 0x0
Load failed
```

After a quick research, I found in the STM32 reference manual, that the flash is mapped to 0x0800 0000. But you instead defined the memory region at 0x000 0000 in your source code in the file `STM32F205RE_flash.ld`. 

I changed that file to this
```
...
MEMORY
{
	ISR_VEC (rx)	: ORIGIN = 0x08000000, LENGTH = 16K     		/* must start at address 0, contains initial vector table */

	/*0x00008000 - 0x0000FFFF, 32k*/
	EEPROM_SIMU (r)	: ORIGIN = 0x08008000, LENGTH = 32K				/* Needs to be as long as 2 flash pages and mapped to flash page boundaries */
	SCRIPT (r)		: ORIGIN = 0x08010000, LENGTH = 64K
	FLASH (rx)		: ORIGIN = 0x08020000, LENGTH = (512K - 128K)
	OPTION_BYTES (r): ORIGIN = 0x1FFFF800, LENGTH = 16
	RAM (xrw)		: ORIGIN = 0x20000000, LENGTH = 128K  /* also change _estack below */
}
...
```

After that change I could load the binary into the MCU with gdb and execute the program. Now it hangs in the `emergencyOperation()` loop, but it runs. 

Do you have any good reason, why you set the flash addresses to 0x0000 0000?

Greets, Karl

**Comment by mduckeck** [comment]
Hi Karl,
we use pullup/pulldown resistors on the pins BOOT0 and BOOT1 to set BOOT0 to high and BOOT1 to low. Please have a look in the STM205 documentation for the description of register SYSCFG. This means that the flash memory is accessible by 0x0000 0000 and 0x0800 0000. 
There is no 'good' reason why we do it that way.
Mathias
