### ISSUE TITLE
The DIO-Module seems to have no EEPROM

### ISSUE THREAD

**Issue by KarlZeilhofer** [RevolutionPi/IODeviceExample#6]
I couldn't find any EEPROM connected to the MCU in the DIO schematic. 

But in src/project.h `#define STM_WITH_EEPROM` was defined. 

I had to uncomment it, otherwise it ran into the `emergencyOperation()`

Could it be, that this code runs on a hardware, which has an EEPROM chip attached?

Greets, Karl

**Comment by mduckeck** [comment]
Hi Karl,
we use an eeprom-simulation that uses the internal flash. There are two flash pages (EEPROM_SIMU) reserved for that in the .ld-file. 
If you enter the function emergencyOperation() you can set a breakpoint in the function applErrHandler() and restart the program. When the program stops at the breakpoint you can go back in the stack trace to find the cause of the error.
But in case of the DIO you can remove the define. It is a remnant from another module which is not used in the DIO.
Mathias

**Comment by KarlZeilhofer** [comment]
Thank you Mathias for your help. I was a bit confused, since there are also files for an external SPI EEPROM. The hint with the backtrace helped also. 

The problem was, that I changed the origin of the flash address, I fixed all that now in the new master branch. I sticked to the 0x0800 0000 address, since this seems to be more common in the STM32 world.
