### ISSUE TITLE
RevPi Compact Library to Control IO

### ISSUE THREAD

**Issue by maguri** [RevolutionPi/IODeviceExample#7]
Hello,
this is not actually an Issue.

**I would like to ask you where can I find a Library to Control de Compact I/O:**
I develop my code in NodeJS but I would be happy If I could find a library in Python at least. Or learn how to access to the Digital I/O.

![image](https://user-images.githubusercontent.com/14354821/120286553-ab648b00-c2be-11eb-8e05-3610fc2ccbf5.png)

Thanks,

**Comment by nbuchwitz** [comment]
Hi @maguri

please have a look at our documentation. With the compact you could either control the I/Os without piControl (https://revolutionpi.de/tutorials/ein-ausgaenge-steuern-ohne-picontrol-compact/) or with piControl (https://revolutionpi.de/tutorials/ein-ausgaenge-steuern-mit-picontrol-compact/). 

If you want to use Python for this I'd recommend the library revpimodio2 in combination with piControl.
